version: '3.3'

services:
  redis:
    image: redis:7.2
    container_name: 'redis'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Redis
    ports:
      - '6379:6379'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/filestorage
    depends_on:
      - mysql
      - redis